name: astronomy_event_booking
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  get: ^4.7.3
  google_fonts: ^8.0.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#2D6A4F"
  color_dark: "#2D6A4F"
  android_12:
    color: "#2D6A4F"
    color_dark: "#2D6A4F"
    icon_background_color: "#2D6A4F"
    icon_background_color_dark: "#2D6A4F"
    image: ""